/**
 * Home-page announcement pill, shown at the top of the hero.
 *
 * Announces the latest stable CodeceptJS release, read at build time from
 * src/content/docs/release.md (regenerated by `bunosh docs`). Links to the
 * release blog post (src/content/docs/blog/codeceptjs-<major>-<minor>.md)
 * when one exists, otherwise to the release notes.
 */
import fs from 'node:fs';
import path from 'node:path';

const DOCS_DIR = path.join(process.cwd(), 'src', 'content', 'docs');
const FALLBACK_VERSION = '4.2';

function latestVersion(): string {
  try {
    const notes = fs.readFileSync(path.join(DOCS_DIR, 'release.md'), 'utf8');
    // First stable release heading: `## [4.2.0](...)` (pre-releases are suffixed).
    const match = notes.match(/^## \[(\d+)\.(\d+)\.\d+\]/m);
    return match ? `${match[1]}.${match[2]}` : FALLBACK_VERSION;
  } catch {
    return FALLBACK_VERSION;
  }
}

function releaseLink(version: string): string {
  const slug = `codeceptjs-${version.replace('.', '-')}`;
  return fs.existsSync(path.join(DOCS_DIR, 'blog', `${slug}.md`)) ? `/blog/${slug}/` : '/release/';
}

const version = latestVersion();

export const announcement = {
  /** Show the announcement pill on the home page. */
  enabled: true,

  /** The message — keep it short, it shows on a single line. */
  text: `CodeceptJS ${version} is out →`,

  /** Where the banner links to. */
  link: releaseLink(version),
};
